### ISSUE TITLE
Validation for HLS Streams failed

### ISSUE THREAD

**Issue by hoffrichterm** [paulhiggs/dvb-i-tools#13]
As described in the Bluebook A177R4 Clause G2.2 the Schema for HLS Delivery is missing.
The file dvbi_v4.0.xsd should import the XSD:
`	<import namespace="vnd:apple:mpegurl" schemaLocation="hls.xsd"/>
`
The hls.xsd contains following schema:

```
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="vnd:apple:mpegurl"
 xmlns:dvbisd="urn:dvb:metadata:servicediscovery:2022b"
 elementFormDefault="qualified" attributeFormDefault="unqualified">
<import namespace="urn:dvb:metadata:servicediscovery:2022b"
 schemaLocation="dvbi_v4.0.xsd"/>
<complexType name="m3u8RefType">
 <complexContent>
 <extension base="dvbisd:ExtensionBaseType">
 <sequence>
 <element name="UriBasedLocation" type="dvbisd:ExtendedURIType"/>
 </sequence>
 </extension>
 </complexContent>
</complexType>
</schema>
```
Then the validation does not fail.

**Comment by paulhiggs** [comment]
Thanks, this is certainly an approach to 'solve' validation of HLS service instances. 
Ideally it should be possible to do this through XML instance document, but libxml is not 'including' additional schemas. This has been reported as [libxmljs2#85](https://github.com/marudor/libxmljs2/issues/85) and [libxml#229](https://gitlab.gnome.org/GNOME/libxml2/-/issues/229)

Recently, I found another XML validator module ([xmllint-wasm](https://github.com/noppa/xmllint-wasm)) that does not depend on libxml. Some simple tests showed that it worked as expected but I have not had time to integrate it into the validation tools

**Comment by hoffrichterm** [comment]
This is strange: On my local Instance i made the changes and it worked fine. I hope I haven't crashed the validator :-)
<img width="974" alt="Bildschirm­foto 2023-03-20 um 17 39 18" src="https://user-images.githubusercontent.com/50859985/226409008-5966260d-0382-4225-93d2-6b9a0091e2ef.png">

**Comment by paulhiggs** [comment]
@hoffrichterm your proposed solution works perfectly, no problem with it.
the X in XML stands for e**X**tensible so it should always be possible to extend an XML instance document using schemas developed by other parties. For example, if there is a BeanStream protocol, the _**XML**_ document should permit this by

```
<Service xmlns="urn:dvb:metadata:servicediscovery:2023" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xmlns:beans="urn:BeanStrean.org:BeanStreamSession"  
  xsi:schemaLocation="urn:BeanStrean.org:BeanStreamSession https://backyerd-gardens.com/Beams/Stream.xsd">

  <ServiceInstance ...>
      <OtherDeliveryParameters extensionName="vnd.beans.stream" xsi:type="beans:streamingStalk">
         <beans:StalkRoot type="spring">Vegepatch.stream</beans:StalkRoot>

```

I will keep this open until I can implement the full solution that supports XML based extensibility.

**Comment by sofia-tsa** [comment]
I'm getting some strange errors when attepting to to validate OtherDeliveryParameters with HLS streams, probably something to do with this issue?
![image](https://github.com/paulhiggs/dvb-i-tools/assets/12542453/44bec0be-6337-4888-b8dd-11e9dd841b6d)

**Comment by paulhiggs** [comment]
This error was being raised because the [schema which is used for validation](https://github.com/paulhiggs/dvb-i-tools/blob/main/dvbi_v4.0-with-hls-hbbtv.xsd) is a little different from the [schema that is published](https://github.com/paulhiggs/dvb-i-tools/blob/main/dvbi_v4.0.xsd). The validation schema includes some schema fragments for validation of HbbTV and HLS since the lint library I use has some importing problems.
