### ISSUE TITLE
Regression in endpoint processing.

### ISSUE THREAD

**Issue by dbcbt** [paulhiggs/dvb-i-tools#16]
Hi Paul,

Just updated to latest dvb-i-tools and Validate SL for: https://dvb-i.net/staging/services.php/de
reports lots of warnings of the form:

`<ProgramInfoEndpoint contentType="application/xml">`
               ` <URI>https://dvb‑i.net/staging/program.php/de/ard</URI>`
            `</ProgramInfoEndpoint>`

`<ProgramInfoEndpoint> is not a valid URL path`

**Comment by paulhiggs** [comment]
Thanks, I have resolved this and fixed two small issues as well.

1. ServiceList@lang attribute is not mandatory for the schema version that you are using (`:2020`). It only becomes required in for `:2022` and beyond.
2. The error (SI022) with description "Delivery parameters are ignored when application controls media playback" is something just added in the latest A177r5 draft. The check is now only performed for relevant versions (i.e. `:2023` and beyond)
