### ISSUE TITLE
Validating GroupInformationTable Basic Description

### ISSUE THREAD

**Issue by hoffrichterm** [paulhiggs/dvb-i-tools#7]
I'm getting a validation error when validating the more episodes endpoint. The reason is a missing BasicDescription Element.
In the Bluebook (R3) the Basic Description Element below the GroupInformationElement is marked as optional (clause 6.11.16.1) and not as mandatory.

I haven't found a rule when a minimum of results is given the BasicDescription Element will be mandatory.
We want to test the more episodes endpoint without pagination.

**Comment by paulhiggs** [comment]
@hoffrichterm - can I close this issue now?

**Comment by hoffrichterm** [comment]
Sorry for my late answer. Yes it works for me.

**Comment by paulhiggs** [comment]
No update needed.
