### ISSUE TITLE
suggestion: validator check for empty XML elements

### ISSUE THREAD

**Issue by hacklsn** [paulhiggs/dvb-i-tools#9]
Recently I stumbled upon an empty `<ProviderName/>` element in a ServiceList. It actually caused the the DVB-I ref-app to crash with un uncaught type error. Could be a useful addition to the validator to check for empty elements - at least mandatory ones - in the shape of `<tag/> ` or `<tag></tag>`

**Comment by paulhiggs** [comment]
This can certainly be added to the validator, but another option would be to add a minimum length in the schema itself.
